- hosts: vagrants
  tasks:
    - name: Update Yum Packages
      become: yes
      yum:
        name: "*"
        state: latest

    - name: Install Essentials Tools
      become: yes
      yum:
        name: ['kernel-devel', 'kernel-headers', 'cmake', 
               'autoconf', 'automake', 'git', 'llvm', 'gcc', 
               'vim', 'curl', 'gnupg2', 'openssl', 'python-devel']
        state: latest
        update_cache: true

    - name: Install Container Tools
      become: yes
      yum:
        name: ['docker']
        state: latest
        update_cache: yes

    - name: Installing python packages
      become: yes
      yum:
        name: ['python-setuptools']
        state: latest
        update_cache: yes

    - name: Installing dependencies
      become: yes
      easy_install:
        name: pip
        state: latest
 
    - name: PIP Install Wheel
      pip:
        name: Wheel
        state: latest
 
    - name: Installing py-docker
      become: yes
      pip:
        name: ['docker', 'docker-compose']
        state: latest

    - name: Install docker-compose
      become: yes
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: +x

    - name: Enable Docker service
      become: yes
      systemd:
          name: docker
          state: started

    - name: Copy host data
      copy: 
        src: ../data
        dest: /home/vagrant

    - name: Build Docker
      become: yes
      docker_compose:
        project_src: /home/vagrant/data/docker
        build: true
        state: present
      register: ouput

    - debug:
        var: ouput