version: '3'
services:
  # ---- proxy
  proxy:
    build: ./nginx
    command: ["nginx", "-g", "daemon off;"]
    container_name: node-proxy
    depends_on:
      - app
    env_file:
      - ./base.env
    ports:
      - 8081:80

  # ---- app
  app:
    build: ./nodejs
    container_name: node-app
    command: ["pm2-runtime", "/var/www/html/app.js"]
    depends_on:
      - db
    env_file:
      - ./base.env
    expose:
      - 8080

  # ---- db
  db:
    build: ./mysql
    container_name: node-db
    env_file:
      - ./base.env
      - ./mysql/mysql.env
    expose:
      - 3306
    volumes:
      - dbdata:/data/mysql

volumes:
  dbdata: