version: '3'
services:
  # ---- proxy
  proxy:
    build: ./nginx
    command: ["nginx", "-g", "daemon off;"]
    container_name: php-proxy
    depends_on:
      - app
    env_file:
      - ./base.env
    ports:
      - 8080:80

  # ---- app
  app:
    build: ./php-fpm74
    container_name: php-app
    env_file:
      - ./base.env
  
  # ---- db
  db:
    build: ./mysql
    container_name: php-db
    env_file:
      - ./base.env
      - ./mysql/mysql.env
    expose:
      - 3306
    volumes:
      - dbdata:/data/mysql

volumes:
  dbdata: